name: user_auth
description: user_auth.
version: 0.0.11
publish_to: none

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.3.2
  in_app_update: ^4.2.5 # Android only
  in_app_review: ^2.0.11
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  jwt_decode: ^0.3.1

  ui_kit_interface:
    git:
      url: https://github.com/tarek360/flutter_kit.git
      ref: 0.0.11
      path: packages/ui_kit_interface

  core:
    git:
      url: https://github.com/tarek360/flutter_kit.git
      ref: 0.0.11
      path: packages/core

dev_dependencies:
  flutter_test:
    sdk: flutter
  global_lints:
    git:
      url: https://github.com/tarek360/flutter_kit.git
      ref: 0.0.11
      path: packages/global_lints

  build_runner: ^2.10.5
  freezed: ^3.2.4
  json_serializable: ^6.11.4

flutter:
