name: ui_kit_interface
description: App resources.
version: 0.0.11
publish_to: none

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  design_system:
    git:
      url: https://github.com/tarek360/flutter_kit.git
      ref: 0.0.11
      path: packages/design_system

  webview_flutter: ^4.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  global_lints:
    git:
      url: https://github.com/tarek360/flutter_kit.git
      ref: 0.0.11
      path: packages/global_lints

flutter:
