name: global_lints
description: Global lints for both apps and all local packages.
version: 0.0.10
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  lint: ^2.8.0
  flutter_lints: ^6.0.0
