name: social_login
description: social_login
version: 0.0.10
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1
  jwt_decode: ^0.3.1

  core:
    git:
      url: https://github.com/tarek360/flutter_kit.git
      ref: 0.0.10
      path: flutter_kit/core

dev_dependencies:
  flutter_test:
    sdk: flutter
  global_lints:
    git:
      url: https://github.com/tarek360/flutter_kit.git
      ref: 0.0.10
      path: flutter_kit/global_lints
flutter:
