name: core
description: App resources.
version: 0.0.11
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.4
  flutter_secure_storage: ^10.0.0
  flutter_riverpod: ^3.2.0
  riverpod_annotation: ^4.0.1
  device_info_plus: ^12.3.0
  package_info_plus: ^9.0.0
  logger: ^2.6.2
  flutter_cache_manager: ^3.4.1
  network:
    git:
      url: https://github.com/tarek360/flutter_networking
      ref: 0.1.12

  firebase_core: ^4.4.0
  firebase_crashlytics: ^5.0.7

  flutter_timezone: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  global_lints:
    git:
      url: https://github.com/tarek360/flutter_kit.git
      ref: 0.0.11
      path: packages/global_lints

  build_runner: ^2.10.5
  freezed: ^3.2.4
  json_serializable: ^6.11.4
  riverpod_generator: ^4.0.2

flutter:
