name: core
description: App resources.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^9.0.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  device_info_plus: ^11.1.1
  package_info_plus: ^8.1.1
  logger: ^2.3.0
  flutter_cache_manager: ^3.3.0
  network:
    git:
      url: https://github.com/tarek360/flutter_networking
      ref: 0.1.12

  firebase_crashlytics: ^4.1.5

  flutter_timezone: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  global_lints:
    git:
      url: git@github.com:tarek360/flutter_kit.git
      ref: main # or a specific branch, tag, or commit
      path: flutter_kit/global_lints

  build_runner: ^2.2.1
  freezed: ^2.1.1
  json_serializable: ^6.4.0

flutter:
